version: '3'
services:
  app:
    container_name: docker-node-mongo-v2
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017          
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'